### ISSUE TITLE
Mixing into other assembly partial class

### ISSUE THREAD

**Issue by Oshi41** [LokiMidgard/PartialMixins#17]
I want to use this library to extend existing partial class.

Let's say I have own library with following class
```
namespace my_lib;

public partial class Context
{
   public int Id {get; set; }
}
```

And now another guy want to extend Context with following interface:
```
namespace other_lib;

public interface IContextExtender
{
  public DateTime Start {get; set; }
}
```

Right now, library allows me to inject functionality in my classes (which I already own).
But is it possible to extend class from other assembly?

It will look like:
```
namespace other_lib;

[MixinInto(typeof(my_lib.Context))]
public interface IContextExtender
{
  public DateTime Start {get; set; }
}
```

And compiler will extend original Context class with IContextExtender interface which give brilliant intelisence support.

Can I make described task with current version? Or it is not supported?

**Comment by LokiMidgard** [comment]
Unfortunally not this library only generates source files that get compiled with yours. So it is only possible to do what you could write in Code. You can't change Classes of another assembly (maybe IL weaving could do it, but I'm not sure).

Eventually the proposed [C# Extensions types](https://github.com/dotnet/csharplang/blob/main/proposals/extensions.md) could be what you are looking for. I think the proposal was  shown in two build conferences. But I can't say when or if it will ever be implemented. 

---

I will close the issue since I can't implement it anyway…
